### ISSUE TITLE
Potentially confusing IP arguments

### ISSUE THREAD

**Issue by ghost** [patri9ck/a2ln-server#26]
In the argparse section it accepts `--notification-ip` and `--pairing-ip` as separate options ([code](https://github.com/patri9ck/a2ln-server/blob/main/a2ln#L92)).

Pairing:
1. client scans qr code containing one IP and one port ([code](https://github.com/patri9ck/a2ln-server/blob/main/a2ln#L251))
2. client sends pair request
3. server responds with either `[b""]` or `[notification_server.port, own_public_key]` ([code](https://github.com/patri9ck/a2ln-server/blob/main/a2ln#L287))

Therefore the client has no option of knowing both IPs.

The only thing i can see this accomplish is to confuse users, which attempt to use mixed IPs and then get connection issues.

in case i overlooked something or it is intended feel free to just close this issue.

**Comment by patri9ck** [comment]
Hey, did you take a look at #22? The reason the command line options were added is to listen only on a certain IP, e.g. 127.0.0.1 instead of *. That could be useful if you use a SSH tunnel. 

The client does not need to know those IPs. It just needs to know the IP of the server in the local network that differs from the IP you can specify with the new arguments. I hope this clarifies it a bit.
